/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ProcessingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'processing' : IDL.Null,
  'failed' : IDL.Null,
});
export const DecodedAudio = IDL.Record({ 'samples' : IDL.Vec(IDL.Float64) });
export const DspBuffer = IDL.Record({
  'processedSamples' : IDL.Vec(IDL.Float64),
});
export const EncodedAudio = IDL.Record({ 'wavData' : IDL.Vec(IDL.Float64) });
export const TripleCheckAnalysisResult = IDL.Record({
  'decodedInput' : DecodedAudio,
  'earlyPipelineOutput' : DspBuffer,
  'noiseDifferences' : IDL.Vec(IDL.Float64),
  'finalEncodedOutput' : EncodedAudio,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Mode = IDL.Variant({ 'audio' : IDL.Null, 'video' : IDL.Null });
export const VideoComparisonData = IDL.Record({
  'activeLayerStack' : IDL.Vec(IDL.Text),
  'jobId' : IDL.Text,
  'editedVideoUrl' : IDL.Text,
  'lastModified' : Time,
  'originalVideoUrl' : IDL.Text,
  'previewGenerated' : IDL.Bool,
});
export const BodyModificationDetails = IDL.Record({
  'bodyShapeAdjusted' : IDL.Bool,
  'complexionAnalysisDone' : IDL.Bool,
  'sizeAdjusted' : IDL.Bool,
  'frameTransitionSmoothed' : IDL.Bool,
  'skinToneMatched' : IDL.Bool,
  'proportionsMaintained' : IDL.Bool,
  'inkColorCorrected' : IDL.Bool,
  'personalizedEnhancement' : IDL.Bool,
  'tattooAreasDetected' : IDL.Bool,
  'adaptiveFilteringApplied' : IDL.Bool,
  'blemishCorrectionDone' : IDL.Bool,
});
export const SpectralData = IDL.Record({
  'frequencyBins' : IDL.Vec(IDL.Nat),
  'duration' : IDL.Float64,
  'frequencyCrossoverPoints' : IDL.Vec(IDL.Nat),
  'timestamp' : Time,
  'intensityValues' : IDL.Vec(IDL.Float64),
});
export const ProcessingJob = IDL.Record({
  'outputFormat' : IDL.Text,
  'aiSelectedEqCurveOptimization' : IDL.Bool,
  'startTime' : Time,
  'status' : ProcessingStatus,
  'denoisingStrength' : IDL.Nat,
  'tripleCheckAnalysisResult' : IDL.Opt(TripleCheckAnalysisResult),
  'aiPromptText' : IDL.Text,
  'dynamicRangeCompression' : IDL.Bool,
  'transientReduction' : IDL.Bool,
  'originalFile' : ExternalBlob,
  'upscalingStrength' : IDL.Nat,
  'dialogueOnlyTrack' : IDL.Opt(ExternalBlob),
  'skinEnhancementApplied' : IDL.Bool,
  'endTime' : IDL.Opt(Time),
  'aiSelectedVoiceClarityEnhancement' : IDL.Bool,
  'enhancedResolution' : IDL.Opt(IDL.Text),
  'renderingOptimized' : IDL.Bool,
  'speechEnhancementApplied' : IDL.Bool,
  'aiSelectedFrequencyResponseAdjustment' : IDL.Bool,
  'fullAudioTrack' : IDL.Opt(ExternalBlob),
  'phaseAlignmentPreserved' : IDL.Bool,
  'tattooMaskingStrength' : IDL.Nat,
  'deepNoiseSuppressionApplied' : IDL.Bool,
  'skinToneAnalysisApplied' : IDL.Bool,
  'aiSelectedFrequencyTargeting' : IDL.Bool,
  'spectralRepair' : IDL.Bool,
  'aiSelectedNormalization' : IDL.Bool,
  'professionalGradeDenoising' : IDL.Bool,
  'mode' : Mode,
  'user' : IDL.Principal,
  'jobId' : IDL.Text,
  'aiSelectedPhaseAwareMasking' : IDL.Bool,
  'aiSelectedAdaptiveFiltering' : IDL.Bool,
  'aiSelectedPrePostGainControl' : IDL.Bool,
  'aiSelectedPhaseAlignment' : IDL.Bool,
  'adaptiveFiltering' : IDL.Bool,
  'lowLightEnhancementStrength' : IDL.Nat,
  'frameMappingCompleted' : IDL.Bool,
  'frequencyTargeting' : IDL.Bool,
  'aiSelectedVoiceIsolation' : IDL.Bool,
  'videoUpscalingApplied' : IDL.Bool,
  'bodyEditingStrength' : IDL.Nat,
  'effectProvider' : IDL.Text,
  'processingTimeAfterUpload' : IDL.Opt(IDL.Int),
  'aiSelectedDynamicRangeCompression' : IDL.Bool,
  'videoComparisonData' : IDL.Opt(VideoComparisonData),
  'statusRelevantForUser' : IDL.Bool,
  'audioVideoSynchronizationMaintained' : IDL.Bool,
  'prePostGainControl' : IDL.Bool,
  'frequencyResponseAdjustment' : IDL.Bool,
  'aiSelectedVolumeConsistency' : IDL.Bool,
  'resolutionConversionCompleted' : IDL.Bool,
  'originalJobId' : IDL.Opt(IDL.Text),
  'voiceClarityEnhancement' : IDL.Bool,
  'eqCurveOptimized' : IDL.Bool,
  'bodyModificationDetails' : IDL.Opt(BodyModificationDetails),
  'skinEnhancementStrength' : IDL.Nat,
  'aiSelectedTimeDomainAdjustments' : IDL.Bool,
  'timeDomainAdjusted' : IDL.Bool,
  'spectralDataGenerated' : IDL.Bool,
  'videoCompressionOptimization' : IDL.Bool,
  'processedFile' : IDL.Opt(ExternalBlob),
  'videoFormatStandardization' : IDL.Bool,
  'volumeConsistencyValidated' : IDL.Bool,
  'aiSelectedSpeechEnhancement' : IDL.Bool,
  'colorGradingApplied' : IDL.Bool,
  'lowLightEnhancementApplied' : IDL.Bool,
  'voiceIsolation' : IDL.Bool,
  'aiSelectedTransientReduction' : IDL.Bool,
  'humanBodyEditingApplied' : IDL.Bool,
  'normalizationApplied' : IDL.Bool,
  'blemishCorrectionApplied' : IDL.Bool,
  'aiSelectedProfessionalGradeDenoising' : IDL.Bool,
  'comparisonTimestamp' : IDL.Opt(Time),
  'colorGradingStrength' : IDL.Nat,
  'effectProviderLogo' : IDL.Text,
  'aiSelectedSpectralRepair' : IDL.Bool,
  'spectralData' : IDL.Opt(SpectralData),
  'aiSelectedSpectralDataGeneration' : IDL.Bool,
  'tattooMaskingApplied' : IDL.Bool,
  'phaseAwareMaskingApplied' : IDL.Bool,
  'videoDenoisingApplied' : IDL.Bool,
  'aiSelectedDeepNoiseSuppression' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const MediaFile = IDL.Record({
  'contentType' : IDL.Text,
  'size' : IDL.Nat,
  'filename' : IDL.Text,
  'uploadTime' : Time,
});
export const VideoComparisonConfig = IDL.Record({
  'active' : IDL.Bool,
  'owner' : IDL.Principal,
  'defaultFilters' : IDL.Vec(IDL.Text),
  'lastConfigUpdate' : Time,
  'synchronizedPlayback' : IDL.Bool,
  'sideBySideEnabled' : IDL.Bool,
  'intensityLevel' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteProcessingJob' : IDL.Func([IDL.Text], [], []),
  'getAllProcessingJobs' : IDL.Func([], [IDL.Vec(ProcessingJob)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyMediaFiles' : IDL.Func([], [IDL.Vec(MediaFile)], ['query']),
  'getMyProcessingJobs' : IDL.Func([], [IDL.Vec(ProcessingJob)], ['query']),
  'getProcessingJob' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ProcessingJob)],
      ['query'],
    ),
  'getTripleCheckAnalysis' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(TripleCheckAnalysisResult)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideoComparisonConfig' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(VideoComparisonConfig)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveVideoComparisonConfig' : IDL.Func(
      [IDL.Text, VideoComparisonConfig],
      [],
      [],
    ),
  'updateJobStatus' : IDL.Func([IDL.Text, ProcessingStatus], [], []),
  'updateTripleCheckAnalysis' : IDL.Func(
      [IDL.Text, TripleCheckAnalysisResult],
      [],
      [],
    ),
  'uploadMediaFile' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        ExternalBlob,
        Mode,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ProcessingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'processing' : IDL.Null,
    'failed' : IDL.Null,
  });
  const DecodedAudio = IDL.Record({ 'samples' : IDL.Vec(IDL.Float64) });
  const DspBuffer = IDL.Record({ 'processedSamples' : IDL.Vec(IDL.Float64) });
  const EncodedAudio = IDL.Record({ 'wavData' : IDL.Vec(IDL.Float64) });
  const TripleCheckAnalysisResult = IDL.Record({
    'decodedInput' : DecodedAudio,
    'earlyPipelineOutput' : DspBuffer,
    'noiseDifferences' : IDL.Vec(IDL.Float64),
    'finalEncodedOutput' : EncodedAudio,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Mode = IDL.Variant({ 'audio' : IDL.Null, 'video' : IDL.Null });
  const VideoComparisonData = IDL.Record({
    'activeLayerStack' : IDL.Vec(IDL.Text),
    'jobId' : IDL.Text,
    'editedVideoUrl' : IDL.Text,
    'lastModified' : Time,
    'originalVideoUrl' : IDL.Text,
    'previewGenerated' : IDL.Bool,
  });
  const BodyModificationDetails = IDL.Record({
    'bodyShapeAdjusted' : IDL.Bool,
    'complexionAnalysisDone' : IDL.Bool,
    'sizeAdjusted' : IDL.Bool,
    'frameTransitionSmoothed' : IDL.Bool,
    'skinToneMatched' : IDL.Bool,
    'proportionsMaintained' : IDL.Bool,
    'inkColorCorrected' : IDL.Bool,
    'personalizedEnhancement' : IDL.Bool,
    'tattooAreasDetected' : IDL.Bool,
    'adaptiveFilteringApplied' : IDL.Bool,
    'blemishCorrectionDone' : IDL.Bool,
  });
  const SpectralData = IDL.Record({
    'frequencyBins' : IDL.Vec(IDL.Nat),
    'duration' : IDL.Float64,
    'frequencyCrossoverPoints' : IDL.Vec(IDL.Nat),
    'timestamp' : Time,
    'intensityValues' : IDL.Vec(IDL.Float64),
  });
  const ProcessingJob = IDL.Record({
    'outputFormat' : IDL.Text,
    'aiSelectedEqCurveOptimization' : IDL.Bool,
    'startTime' : Time,
    'status' : ProcessingStatus,
    'denoisingStrength' : IDL.Nat,
    'tripleCheckAnalysisResult' : IDL.Opt(TripleCheckAnalysisResult),
    'aiPromptText' : IDL.Text,
    'dynamicRangeCompression' : IDL.Bool,
    'transientReduction' : IDL.Bool,
    'originalFile' : ExternalBlob,
    'upscalingStrength' : IDL.Nat,
    'dialogueOnlyTrack' : IDL.Opt(ExternalBlob),
    'skinEnhancementApplied' : IDL.Bool,
    'endTime' : IDL.Opt(Time),
    'aiSelectedVoiceClarityEnhancement' : IDL.Bool,
    'enhancedResolution' : IDL.Opt(IDL.Text),
    'renderingOptimized' : IDL.Bool,
    'speechEnhancementApplied' : IDL.Bool,
    'aiSelectedFrequencyResponseAdjustment' : IDL.Bool,
    'fullAudioTrack' : IDL.Opt(ExternalBlob),
    'phaseAlignmentPreserved' : IDL.Bool,
    'tattooMaskingStrength' : IDL.Nat,
    'deepNoiseSuppressionApplied' : IDL.Bool,
    'skinToneAnalysisApplied' : IDL.Bool,
    'aiSelectedFrequencyTargeting' : IDL.Bool,
    'spectralRepair' : IDL.Bool,
    'aiSelectedNormalization' : IDL.Bool,
    'professionalGradeDenoising' : IDL.Bool,
    'mode' : Mode,
    'user' : IDL.Principal,
    'jobId' : IDL.Text,
    'aiSelectedPhaseAwareMasking' : IDL.Bool,
    'aiSelectedAdaptiveFiltering' : IDL.Bool,
    'aiSelectedPrePostGainControl' : IDL.Bool,
    'aiSelectedPhaseAlignment' : IDL.Bool,
    'adaptiveFiltering' : IDL.Bool,
    'lowLightEnhancementStrength' : IDL.Nat,
    'frameMappingCompleted' : IDL.Bool,
    'frequencyTargeting' : IDL.Bool,
    'aiSelectedVoiceIsolation' : IDL.Bool,
    'videoUpscalingApplied' : IDL.Bool,
    'bodyEditingStrength' : IDL.Nat,
    'effectProvider' : IDL.Text,
    'processingTimeAfterUpload' : IDL.Opt(IDL.Int),
    'aiSelectedDynamicRangeCompression' : IDL.Bool,
    'videoComparisonData' : IDL.Opt(VideoComparisonData),
    'statusRelevantForUser' : IDL.Bool,
    'audioVideoSynchronizationMaintained' : IDL.Bool,
    'prePostGainControl' : IDL.Bool,
    'frequencyResponseAdjustment' : IDL.Bool,
    'aiSelectedVolumeConsistency' : IDL.Bool,
    'resolutionConversionCompleted' : IDL.Bool,
    'originalJobId' : IDL.Opt(IDL.Text),
    'voiceClarityEnhancement' : IDL.Bool,
    'eqCurveOptimized' : IDL.Bool,
    'bodyModificationDetails' : IDL.Opt(BodyModificationDetails),
    'skinEnhancementStrength' : IDL.Nat,
    'aiSelectedTimeDomainAdjustments' : IDL.Bool,
    'timeDomainAdjusted' : IDL.Bool,
    'spectralDataGenerated' : IDL.Bool,
    'videoCompressionOptimization' : IDL.Bool,
    'processedFile' : IDL.Opt(ExternalBlob),
    'videoFormatStandardization' : IDL.Bool,
    'volumeConsistencyValidated' : IDL.Bool,
    'aiSelectedSpeechEnhancement' : IDL.Bool,
    'colorGradingApplied' : IDL.Bool,
    'lowLightEnhancementApplied' : IDL.Bool,
    'voiceIsolation' : IDL.Bool,
    'aiSelectedTransientReduction' : IDL.Bool,
    'humanBodyEditingApplied' : IDL.Bool,
    'normalizationApplied' : IDL.Bool,
    'blemishCorrectionApplied' : IDL.Bool,
    'aiSelectedProfessionalGradeDenoising' : IDL.Bool,
    'comparisonTimestamp' : IDL.Opt(Time),
    'colorGradingStrength' : IDL.Nat,
    'effectProviderLogo' : IDL.Text,
    'aiSelectedSpectralRepair' : IDL.Bool,
    'spectralData' : IDL.Opt(SpectralData),
    'aiSelectedSpectralDataGeneration' : IDL.Bool,
    'tattooMaskingApplied' : IDL.Bool,
    'phaseAwareMaskingApplied' : IDL.Bool,
    'videoDenoisingApplied' : IDL.Bool,
    'aiSelectedDeepNoiseSuppression' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const MediaFile = IDL.Record({
    'contentType' : IDL.Text,
    'size' : IDL.Nat,
    'filename' : IDL.Text,
    'uploadTime' : Time,
  });
  const VideoComparisonConfig = IDL.Record({
    'active' : IDL.Bool,
    'owner' : IDL.Principal,
    'defaultFilters' : IDL.Vec(IDL.Text),
    'lastConfigUpdate' : Time,
    'synchronizedPlayback' : IDL.Bool,
    'sideBySideEnabled' : IDL.Bool,
    'intensityLevel' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteProcessingJob' : IDL.Func([IDL.Text], [], []),
    'getAllProcessingJobs' : IDL.Func([], [IDL.Vec(ProcessingJob)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyMediaFiles' : IDL.Func([], [IDL.Vec(MediaFile)], ['query']),
    'getMyProcessingJobs' : IDL.Func([], [IDL.Vec(ProcessingJob)], ['query']),
    'getProcessingJob' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ProcessingJob)],
        ['query'],
      ),
    'getTripleCheckAnalysis' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TripleCheckAnalysisResult)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideoComparisonConfig' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(VideoComparisonConfig)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveVideoComparisonConfig' : IDL.Func(
        [IDL.Text, VideoComparisonConfig],
        [],
        [],
      ),
    'updateJobStatus' : IDL.Func([IDL.Text, ProcessingStatus], [], []),
    'updateTripleCheckAnalysis' : IDL.Func(
        [IDL.Text, TripleCheckAnalysisResult],
        [],
        [],
      ),
    'uploadMediaFile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          ExternalBlob,
          Mode,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };